### ISSUE TITLE
the update/update.swu is zero bytes

### ISSUE THREAD

**Issue by logiota** [ultimateshadsform/Anycubic-Kobra-2-Series-Tools#3]
sh pack.sh
-e Checking tool: grep
-e Checking tool: md5sum
-e Checking tool: openssl
-e Checking tool: wc
-e Checking tool: awk
-e Checking tool: sha256sum
-e Checking tool: mksquashfs
-e SUCCESS: All tools are available
-e Deleting the existing rootfs
Parallel mksquashfs: Using 10 processors
Creating 4.0 filesystem on rootfs, block size 131072.
[===================================================================|] 2219/2219 100%

Exportable Squashfs 4.0 filesystem, xz compressed, data block size 131072
	compressed data, compressed metadata, compressed fragments,
	compressed xattrs, compressed ids
	duplicates are removed
Filesystem size 48737.39 Kbytes (47.60 Mbytes)
	38.19% of uncompressed filesystem size (127606.10 Kbytes)
Inode table size 15472 bytes (15.11 Kbytes)
	24.99% of uncompressed inode table size (61916 bytes)
Directory table size 15666 bytes (15.30 Kbytes)
	43.62% of uncompressed directory table size (35913 bytes)
Number of duplicate files found 31
Number of inodes 1762
Number of files 1369
Number of fragments 117
Number of symbolic links 264
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 129
Number of hard-links 0
Number of ids (unique uids + gids) 1
Number of uids 1
	root (0)
Number of gids 1
	wheel (0)
cpio: No such format 'crc'

-e Packing done: Use the file update/update.swu to do USB update

**Comment by ultimateshadsform** [comment]
Do you have pycryptodome installed?

**Comment by logiota** [comment]
yes using base env through miniforge3(conda)

**Comment by ultimateshadsform** [comment]
Do you have all the developer dependencies installed? For ubuntu it's sudo apt install build-essential

**Comment by logiota** [comment]
yes command line tools are the equivalent on MacOS, 
can I get verbose output somehow?
do you know what the error indicates:
cpio: No such format 'crc'

**Comment by ultimateshadsform** [comment]
No idea. Maybe install another version of cpio?

The regular linux version.

**Comment by logiota** [comment]
it is the latest version I can get, even with package manager
VM here I come :P

**Comment by ultimateshadsform** [comment]
> it is the latest version I can get, even with package manager VM here I come :P Kali should work right?

Yeah I use ubuntu

**Comment by ultimateshadsform** [comment]
Closing this for now. If you have any issue feel free to comment.

**Comment by logiota** [comment]
which python version is it supposed to be?

**Comment by ultimateshadsform** [comment]
pip install scp ?

**Comment by ultimateshadsform** [comment]
I used 3.12
